name: Docker CI

on:
  push:
      branches:
        - main
        - "release/**"
        - "feature/arm-platform-support"
      tags:        
        - v*.* 
  pull_request:
      branches:
        - main
        - "release/**"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        if: startsWith(github.ref, 'refs/tags/')
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          tags: timoschlueter/nightscout-librelink-up:${{github.sha}},timoschlueter/nightscout-librelink-up:${{github.ref_name}},timoschlueter/nightscout-librelink-up:latest
      -
        name: Image digest
        if: startsWith(github.ref, 'refs/tags/')
        run: echo ${{ steps.docker_build.outputs.digest }}
